name: Rust-wasm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-bindgen-action@v0.1.0
      #with:
        # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
        #version: # optional, default is latest
    - name: Install GUI dependencies
      run: sudo apt update && sudo apt install -y librust-glib-dev librust-pangocairo-dev librust-atk-dev librust-gdk-sys-dev librust-libudev-sys-dev librust-alsa-sys-dev
    - name: Rust check
      run: cargo c
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Install Wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Build Wasm target
      run: cargo c --target wasm32-unknown-unknown
